# Generated by Django 5.1.7 on 2025-03-15 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='chassis_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='The chassis number must consist of 5 letters at the beginning, followed by 10 alphanumeric characters.', regex='^[A-Z]{5}[A-Z0-9]{10}$')]),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='sim_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='The SIM number must consist of 16 digits.', regex='^\\d{16}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_regex',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='The phone number must start with a country code and be 8-15 digits long.', regex='^\\+?[1-9]\\d{7,14}$')]),
        ),
    ]
