# Generated by Django 5.1.7 on 2025-04-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_ticket_seat_number_alter_ticket_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='departure_time',
            field=models.CharField(max_length=5),
        ),
    ]
